<?php ob_start(); ?>
<?php
session_start();
include "../include/config.php";
$msid=$_SESSION['STUDENT_ID'];
if(!isset($_SESSION['STUDENT_ID'])){
  $url=$host."/OSQR/";
    header('Location:'.$url);
    die();
}
$sql="SELECT user_name from student where user_id=$msid";
$res=mysqli_query($conn,$sql) or die("You are not register");
$nm=mysqli_fetch_assoc($res)['user_name'];
ob_end_flush();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student - OSQR</title>
    <link rel="stylesheet" href="../assets/css/bootstrap.css" />
    <style>
    .he{
        font-size:1.2rem;
        font-weight:600;
        color:#fff !important;
    }
    </style>
</head>
<body>
<!-- header -->
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#" style="font-size:1.5rem;color:#fff;">OSQR STUDENT</a>
    <button class="navbar-toggler" style="background: #fff;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link he" aria-current="page" href="../index.php">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link he" href="#">Classes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link he" href="#">Performance</a>
        </li>
        <li class="nav-item">
          <a class="nav-link he" href="/osqr/teacher/logout.php">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!--END Header-->

<div style="width:100%;background:#e7e7e7;">
<!-- Write Code Here-->
<div class="container p-4">
<div class="card p-3 mt-4">
<h1>Welcome <strong class="text-success"><?php echo $nm; ?></strong></h1>
<?php if(isset($_GET['att'])){
echo '<div class="alert alert-success mt-2 mb-2" role="alert">Your Attendance Marked Successfully</div>';
}
?>
</div>

<div class="card p-3 mt-3">
<div class="row">
<div class="col-md-6">
<img src="../assets/img/qr-code.jpg" style="width:100%;" class="img-fluid"/>
</div>
<div class="col-md-6">
<div style="margin-top: 2.5rem;line-height: 2;">
<h3>Scan QR Code and Marked your Attendence. It's Simple</h3>
<p>Just Scan Qr Code generated by Your Teacher, and Marked Your Attendence.</p>
<?php if(isset($_GET['att'])){
  $t=true;
} else{
  echo'
  <button id="start_scan" class="btn btn-primary btn-lg" onclick="scanner_init()">Scan QR</button>';
}
?>

<button class="btn btn-danger btn-lg" type="button" id="btn_loader" style="display:none;">
  <span class="spinner-border spinner-border-sm text-white" role="status" aria-hidden="true"></span>
  Marking Attendance..
</button>
<p class="mt-2" id="content"></p>
</div>
</div>
</div>



</div>
<div class="card p-3 mt-3" id="preview_qr" style="display:none;">

<video id="preview" class="mb-2 img-fluid mx-auto">
</video>
<div class="btn-group btn-group-toggle mb-5" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="radio" name="options" value="1" autocomplete="off"> Front Camera
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" value="2" autocomplete="off" checked> Back Camera
  </label>
</div>
</div>
</div>
</div>



<!--END HERE MAIN DIV-->
</div>
<script src="../assets/js/bootstrap.bundle.js"></script>
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/instascan.min.js"></script>

<script type="text/javascript">
function DisplayCurrentTime() {
        var date = new Date();
        var hours = date.getHours() > 12 ? date.getHours() - 12 : date.getHours();
        hours = hours < 10 ? "0" + hours : hours;
        var minutes = date.getMinutes() < 10 ? "0" + date.getMinutes() : date.getMinutes();
        time = hours + ":" + minutes;
        return time;
    };
  function scanner_init(){
    var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
    scanner.addListener('scan',function(content){
      scanner.stop();
        $('#preview_qr').hide();
        $('#start_scan').hide();
        $('#btn_loader').show();
        content+="&astuid="+<?php echo $msid;?>;
        content+="&scan_time="+DisplayCurrentTime();
        window.location.href=content;
    });
    Instascan.Camera.getCameras().then(function (cameras){
        if(cameras.length>0){
            scanner.start(cameras[1]);
            $('[name="options"]').on('change',function(){
                if($(this).val()==1){
                    if(cameras[0]!=""){
                        scanner.start(cameras[0]);
                    }else{
                        alert('No Front camera found!');
                    }
                }else if($(this).val()==2){
                    if(cameras[1]!=""){
                        scanner.start(cameras[1]);
                    }else{
                        alert('No Back camera found!');
                    }
                }
            });
        }else{
            alert('No cameras found.');
        }
    }).catch(function(e){
        console.error(e);
        alert(e);
    });
    $('#preview_qr').show();
  }
</script>
</body>
</html>